// Bundles src/widget/chat.ts (incl. the @modelcontextprotocol/ext-apps guest
// bridge) with esbuild, inlines it + chat.css into chat.html, and emits a
// single self-contained HTML string as src/widget.generated.ts.
//
// The widget must be one self-contained document because the host renders it
// via srcdoc in a sandboxed iframe — no external network fetches.
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const widgetDir = resolve(root, "src/widget");

const result = await build({
  entryPoints: [resolve(widgetDir, "chat.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2020",
  write: false,
  minify: true,
  legalComments: "none",
});
const js = result.outputFiles[0].text;
const css = readFileSync(resolve(widgetDir, "chat.css"), "utf8");

let html = readFileSync(resolve(widgetDir, "chat.html"), "utf8");
// Use replacement functions so `$` sequences in css/js aren't treated specially.
html = html.replace("/*__STYLE__*/", () => css);
html = html.replace("/*__SCRIPT__*/", () => js.replace(/<\/script/gi, "<\\/script"));

const out =
  `// AUTO-GENERATED by scripts/build-widget.mjs — do not edit.\n` +
  `export const CHAT_WIDGET_HTML = ${JSON.stringify(html)};\n`;
writeFileSync(resolve(root, "src/widget.generated.ts"), out);

console.log(
  `[build-widget] wrote src/widget.generated.ts (${html.length} B html, ${js.length} B js)`,
);
